services:
  - type: web
    name: sisincop-native
    env: node
    plan: free
    buildCommand: node render-override.js
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_VERSION
        value: 20.18.1