services:
  - type: web
    name: sisincop
    env: node
    plan: free
    buildCommand: npm run build:client && npm run build:server
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
    autoDeploy: false